OBJECTS=main.o glFunc.o
SOURCES=*.cpp *.h
GCC=clang++
CFLAGS=-std=c++11 -stdlib=libc++ -g3 -Wall -O0 -Wno-deprecated -Werror -I./lib/FFT_CODE
LDFLAGS=-framework OpenGL -framework GLUT -framework SFML -framework sfml-audio
PROG=visualizer

all: $(PROG)

$(PROG): $(OBJECTS)
	$(GCC) $(LDFLAGS) -o $(PROG) $^

.cpp.o:
	$(GCC) $(CFLAGS) -c $<

clean:
	-rm $(OBJECTS) $(PROG)


