FFTWDIR=/usr/local/Cellar/fftw/3.3.3
FFTWLIB=$(FFTWDIR)/lib
OBJECTS=main.o glFunc.o
SOURCES=*.cpp *.h
GCC=clang++
CFLAGS=-std=c++11 -stdlib=libc++ -g3 -Wall -O0 -Wno-deprecated -Werror
LDFLAGS=-framework OpenGL -framework GLUT -framework SFML -framework sfml-audio -L$(FFTWLIB) -lfftw3f
PROG=visualizer

all: $(PROG)

$(PROG): $(OBJECTS)
	$(GCC) $(LDFLAGS) -o $(PROG) $^

.cpp.o:
	$(GCC) $(CFLAGS) -c $<

clean:
	-rm $(OBJECTS) $(PROG)


